src/controllers/AdminController.php
<?php

namespace app\controllers;

use yii\web\Controller;

class AdminController extends Controller
{
    public function actionMail()
    {
        return $this->render('mail', []);
    }
}

src/controllers/MailingController.php
<?php

namespace app\controllers;

use app\models\forms\MailingForm;
use app\models\search\UserSearch;
use app\models\search\MailTemplateSearch;
use Yii;
use app\models\tables\Mailing;
use app\models\search\MailingSearch;
use yii\filters\AccessControl;
use yii\web\Controller;
use yii\web\NotFoundHttpException;
use yii\filters\VerbFilter;

/**
 * MailingController implements the CRUD actions for Mailing model.
 */
class MailingController extends Controller
{
    /**
     * @inheritdoc
     */
    public function behaviors()
    {
        return [
            'verbs' => [
                'class' => VerbFilter::className(),
                'actions' => [
                    'delete' => ['POST'],
                ],
            ],
            'access' => [
                'class' => AccessControl::className(),
                'rules' => [
                    [
                        'allow' => true,
                        'actions' => ['create', 'update', 'delete'],
                        'roles' => ['@']
                    ],
                    [
                        'allow' => true,
                        'actions' => ['list', 'view'],
                        'roles' => ['?', '@']
                    ],
                ]
            ]
        ];
    }

    /**
     * Lists all Mailing models.
     *
     * @return mixed
     */
    public function actionList()
    {
        $searchModel = new MailingSearch();
        $dataProvider = $searchModel->search(Yii::$app->request->queryParams);

        return $this->render('list', [
            'searchModel' => $searchModel,
            'dataProvider' => $dataProvider,
        ]);
    }

    /**
     * Displays a single Mailing model.
     *
     * @param integer $id
     * @return mixed
     */
    public function actionView($id)
    {
        return $this->render('view', [
            'model' => $this->findModel($id),
        ]);
    }

    /**
     * Creates a new Mailing model.
     * If creation is successful, the browser will be redirected to the 'view' page.
     *
     * @return mixed
     */
    public function actionCreate()
    {
        $mailing = new MailingForm();
        $userSearch = new UserSearch();
        $userDataProvider = $userSearch->search(Yii::$app->request->queryParams);

        $mailSearch = new MailTemplateSearch();
        $mailDataProvider = $mailSearch->search(Yii::$app->request->queryParams);

        if ($mailing->load(Yii::$app->request->post()) && $mailing->validate() && $mailing->save()) {
            return $this->redirect(['list']);
        }
        return $this->render(
            'create',
            compact('mailing', 'userSearch', 'userDataProvider', 'mailSearch', 'mailDataProvider')
        );
    }

    /**
     * Updates an existing Mailing model.
     * If update is successful, the browser will be redirected to the 'view' page.
     *
     * @param integer $id
     * @return mixed
     */
    public function actionUpdate($id)
    {
        $model = $this->findModel($id);

        if ($model->load(Yii::$app->request->post()) && $model->save()) {
            return $this->redirect(['view', 'id' => $model->id]);
        }
        return $this->render('update', ['model' => $model,]);
    }

    /**
     * Deletes an existing Mailing model.
     * If deletion is successful, the browser will be redirected to the 'index' page.
     *
     * @param integer $id
     * @return mixed
     */
    public function actionDelete($id)
    {
        $this->findModel($id)->delete();

        return $this->redirect(['list']);
    }

    /**
     * Finds the Mailing model based on its primary key value.
     * If the model is not found, a 404 HTTP exception will be thrown.
     *
     * @param integer $id
     * @return Mailing the loaded model
     * @throws NotFoundHttpException if the model cannot be found
     */
    protected function findModel($id)
    {
        $model = Mailing::findOne($id);
        if (null === $model) {
            throw new NotFoundHttpException('The requested page does not exist.');
        }
        return $model;
    }
}

src/views/mailing/_form.php
<?php

use app\models\tables\Mailing;
use app\models\tables\MailTemplate;
use kartik\datetime\DateTimePicker;
use yii\helpers\Html;
use yii\widgets\ActiveForm;

/* @var $this yii\web\View */
/* @var $model app\models\tables\Mailing */
/* @var $form yii\widgets\ActiveForm */
?>

<div class="mailing-form">

    <?php $form = ActiveForm::begin(); ?>

    <?= $form->field($model, 'user_id')->textInput() ?>

    <?= $form->field($model, 'mail_template_id')->dropDownList(MailTemplate::getTemplatesList()) ?>

    <?= $form->field($model, 'status')->dropDownList([
        Mailing::ACTIVE => \Yii::t('mail', 'Active'),
        Mailing::INACTIVE => \Yii::t('mail', 'Not active'),
    ], [
        'prompt' => \Yii::t('mail', 'Choose status'),
    ]) ?>

    <?= $form->field($model, 'placeholders')->textarea(['rows' => 6]) ?>

    <?= $form->field($model, 'date_send')->widget(DateTimePicker::className(), [
        'options' => ['placeholder' => \Yii::t('mail', 'Enter send time')],
        'pluginOptions' => [
            'autoclose' => true,
            'startDate' => date("yy-mm-dd"),
            'minDate' => false,
        ],
    ]); ?>

    <div class="form-group">
        <?= Html::submitButton($model->isNewRecord ? Yii::t('mail', 'Create') : Yii::t('mail', 'Update'), ['class' => $model->isNewRecord ? 'btn btn-success' : 'btn btn-primary']) ?>
    </div>

    <?php ActiveForm::end(); ?>

</div>

src/views/mailing/_search.php
<?php

use app\models\tables\MailTemplate;
use yii\helpers\Html;
use yii\widgets\ActiveForm;

/* @var $this yii\web\View */
/* @var $model app\models\tables\MailingSearch */
/* @var $form yii\widgets\ActiveForm */
?>

<div class="mailing-search">

    <?php $form = ActiveForm::begin([
        'action' => ['index'],
        'method' => 'get',
    ]); ?>

    <?= $form->field($model, 'id') ?>

    <?= $form->field($model, 'user_id') ?>

    <?= $form->field($model, 'mail_template_id')->dropDownList(MailTemplate::getTemplatesList()) ?>

    <?= $form->field($model, 'status') ?>

    <?= $form->field($model, 'placeholders') ?>

    <?php  echo $form->field($model, 'created_at') ?>

    <?php  echo $form->field($model, 'date_send') ?>

    <div class="form-group">
        <?= Html::submitButton(Yii::t('mail', 'Search'), ['class' => 'btn btn-primary']) ?>
        <?= Html::resetButton(Yii::t('mail', 'Reset'), ['class' => 'btn btn-default']) ?>
    </div>

    <?php ActiveForm::end(); ?>

</div>

src/views/mailing/create.php
<?php

use app\models\tables\User;
use drsdre\wizardwidget\WizardWidget;
use kartik\datetime\DateTimePicker;
use kartik\grid\GridView;
use yii\helpers\ArrayHelper;
use yii\helpers\Html;
use yii\widgets\ActiveForm;
/* @var $this yii\web\View */
/* @var $mailing app\models\tables\Mailing */

$this->title = Yii::t('mail', 'Create Mailing');
$this->params['breadcrumbs'][] = ['label' => 'Mail Admin page', 'url' => ['admin/mail']];
$this->params['breadcrumbs'][] = ['label' => Yii::t('mail', 'Mailings'), 'url' => ['list']];
$this->params['breadcrumbs'][] = $this->title;

echo "PHP: " . PHP_VERSION . "<br>";
echo "ICU: " . INTL_ICU_VERSION . "<br>";
echo "ICU Data: " . INTL_ICU_DATA_VERSION . "<br>";
?>
<div class="mailing-create">

    <h1><?= Html::encode($this->title) ?></h1>

    <?php $form = ActiveForm::begin(['id' => 'mailingForm']); ?>
    <?= Html::activeLabel($mailing, 'templateId'); ?>
    <?= Html::error($mailing, 'templateId', ['style' => 'color: red;', 'class' => 'has-error']); ?>
    <?= Html::activeHiddenInput($mailing, 'templateId', ['id' => 'templateId']); ?>

    <?= Html::activeLabel($mailing, 'dateSend'); ?>
    <?= Html::error($mailing, 'dateSend', ['style' => 'color: red;', 'class' => 'has-error']); ?>
    <?= Html::activeHiddenInput($mailing, 'dateSend', ['id' => 'dateSend']); ?>

    <?= Html::activeLabel($mailing, 'usersId'); ?>
    <?= Html::error($mailing, 'usersId', ['style' => 'color: red;', 'class' => 'has-error']); ?>
    <?= Html::activeHiddenInput($mailing, 'usersId', ['id' => 'usersId']); ?>

    <?= Html::activeLabel($mailing, 'placeholders'); ?>
    <?= Html::error($mailing, 'placeholders', ['style' => 'color: red;', 'class' => 'has-error']); ?>
    <?= Html::activeHiddenInput($mailing, 'placeholders', ['id' => 'placeholders']); ?>

    <?php ActiveForm::end(); ?>

    <?php

    $selectUsers = GridView::widget([
        'id' => 'usersGrid',
        'dataProvider' => $userDataProvider,
        'filterModel' => $userSearch,
        'pjax' => true,
        'export' => false,
        'pjaxSettings' => [
            'neverTimeout' => true,
            'beforeGrid' => '<h3>Choose users</h3>',
        ],
        'columns' => [
            ['class' => 'kartik\grid\SerialColumn'],
            'username',
            'created_at:datetime',
            [
                'class' => 'kartik\grid\BooleanColumn',
                'attribute' => 'status',
                'vAlign' => 'middle'
            ],
            [
                'class' => '\kartik\grid\CheckboxColumn',
                'checkboxOptions' => function ($model) {
                    return [
                        "value" => $model->id,
                    ];
                },
            ],
        ],
    ]);

    $selectTemplates = GridView::widget([
        'id' => 'templatesGrid',
        'dataProvider' => $mailDataProvider,
        'filterModel' => $mailSearch,
        'pjax' => true,
        'export' => false,
        'pjaxSettings' => [
            'neverTimeout' => true,
            'beforeGrid' => '<h3>Choose mail template</h3>',
        ],
        'columns' => [
            [
                'class' => 'kartik\grid\SerialColumn',
                'contentOptions' => ['class' => 'kartik-sheet-style'],
                'width' => '36px',
                'header' => '#',
                'headerOptions' => ['class' => 'kartik-sheet-style']
            ],
            [
                'class' => 'kartik\grid\RadioColumn',
                'width' => '36px',
                'headerOptions' => ['class' => 'kartik-sheet-style'],
                'radioOptions' => function ($model, $key, $index, $column) {
                    return [
                        'value' => $model->id,
                    ];
                }
            ],
            [
                'attribute' => 'name',
                'width' => '150px',
            ],
            [
                'attribute' => 'user_id',
                'label' => 'Author',
                'vAlign' => 'middle',
                'width' => '180px',
                'value' => function ($model, $key, $index, $widget) {
                    return Html::a(
                        $model->user->username,
                        '#',
                        ['title' => 'View author detail']
                    );
                },
                'filterType' => GridView::FILTER_SELECT2,
                'filter' => ArrayHelper::map(User::find()->orderBy('username')->asArray()->all(), 'id', 'username'),
                'filterWidgetOptions' => [
                    'pluginOptions' => ['allowClear' => true],
                ],
                'filterInputOptions' => ['placeholder' => 'Any author'],
                'format' => 'raw'
            ],
            'created_at:datetime',
        ],
    ]);

    $selectData = DateTimePicker::widget([
        'options' => ['placeholder' => 'Select send time'],
        'name' => 'widgetDateSend',
        'id' => 'widgetDateSend',
        'pluginOptions' => [
            'format' => 'yyyy-m-d H:i',
            'startDate' => date('Y-m-d'),
            'todayHighlight' => true
        ]
    ]);
    $templatePlaceholders = Html::label('User name') . '<br>';
    $templatePlaceholders .= Html::input('text', 'user', '', ['class' => 'form-control']) . '<br>';
    $templatePlaceholders .= Html::label('Location') . '<br>';
    $templatePlaceholders .= Html::input('text', 'location', '', ['class' => 'form-control']) . '<br>';
    $templatePlaceholders .= Html::label('Date') . '<br>';
    $templatePlaceholders .= Html::input('text', 'date', '', ['class' => 'form-control']) . '<br>';
    $templatePlaceholders = "<div class='placeholders'>$templatePlaceholders </div>";

    $wizardConfig = [
        'id' => 'stepwizard',
        'steps' => [
            'users' => [
                'title' => 'Users',
                'icon' => 'glyphicon glyphicon-user',
                'content' => $selectUsers,
                'buttons' => [
                    'next' => [
                        'title' => 'Next',
                        'options' => [
                            'class' => 'btn btn-default',
                            'id' => 'usersSelected'
                        ],
                    ],
                ],
            ],
            'templates' => [
                'title' => 'Templates',
                'icon' => 'glyphicon glyphicon-file',
                'content' => $selectTemplates,
            ],
            'date' => [
                'title' => 'Date',
                'icon' => 'glyphicon glyphicon-calendar',
                'content' => $selectData . $templatePlaceholders,
                'buttons' => [
                    'next' => [
                        'title' => 'Next',
                        'options' => [
                            'class' => 'btn btn-default',
                        ],
                    ],
                ],
            ],
        ],
        'complete_content' => Html::submitButton('Save', ['class' => 'btn btn-primary', 'id' => 'createMailing']),
        'start_step' => 'users',
    ];

    ?>
    <?= WizardWidget::widget($wizardConfig); ?>

</div>

src/views/mailing/list.php
<?php

use yii\helpers\Html;
use yii\grid\GridView;
use yii\widgets\Pjax;

/* @var $this yii\web\View */
/* @var $searchModel app\models\tables\MailingSearch */
/* @var $dataProvider yii\data\ActiveDataProvider */

$this->title = Yii::t('mail', 'Mailings');
$this->params['breadcrumbs'][] = ['label' => 'Mail Admin page', 'url' => ['admin/mail']];
$this->params['breadcrumbs'][] = $this->title;
?>
<div class="mailing-index">

    <h1><?= Html::encode($this->title) ?></h1>
    <?php // echo $this->render('_search', ['model' => $searchModel]); ?>

    <p>
        <?= Html::a(Yii::t('mail', 'Create Mailing'), ['create'], ['class' => 'btn btn-success']) ?>
    </p>
    <?php Pjax::begin(); ?>
    <?= GridView::widget([
        'dataProvider' => $dataProvider,
        'filterModel' => $searchModel,
        'columns' => [
            ['class' => 'yii\grid\SerialColumn'],
            'user.username',
            'mailTemplate.name',
            'status',
            'placeholders:ntext',
             'created_at:datetime',
             'date_send:datetime',

            ['class' => 'yii\grid\ActionColumn'],
        ],
    ]); ?>
    <?php Pjax::end(); ?></div>

src/views/mailing/update.php
<?php

use yii\helpers\Html;

/* @var $this yii\web\View */
/* @var $model app\models\tables\Mailing */

$this->title = Yii::t('mail', 'Update {modelClass}: ', [
    'modelClass' => 'Mailing',
]) . $model->id;
$this->params['breadcrumbs'][] = ['label' => 'Mail Admin page', 'url' => ['admin/mail']];
$this->params['breadcrumbs'][] = ['label' => Yii::t('mail', 'Mailings'), 'url' => ['list']];
$this->params['breadcrumbs'][] = ['label' => $model->id, 'url' => ['view', 'id' => $model->id]];
$this->params['breadcrumbs'][] = Yii::t('mail', 'Update');
?>
<div class="mailing-update">

    <h1><?= Html::encode($this->title) ?></h1>

    <?= $this->render('_form', [
        'model' => $model,
    ]) ?>

</div>

src/views/mailing/view.php
<?php

use yii\helpers\Html;
use yii\widgets\DetailView;

/* @var $this yii\web\View */
/* @var $model app\models\tables\Mailing */

$this->title = $model->id;
$this->params['breadcrumbs'][] = ['label' => 'Mail Admin page', 'url' => ['admin/mail']];
$this->params['breadcrumbs'][] = ['label' => Yii::t('mail', 'Mailings'), 'url' => ['list']];
$this->params['breadcrumbs'][] = $this->title;
?>
<div class="mailing-view">

    <h1><?= Html::encode($this->title) ?></h1>

    <p>
        <?= Html::a(Yii::t('mail', 'Update'), ['update', 'id' => $model->id], ['class' => 'btn btn-primary']) ?>
        <?= Html::a(Yii::t('mail', 'Delete'), ['delete', 'id' => $model->id], [
            'class' => 'btn btn-danger',
            'data' => [
                'confirm' => Yii::t('mail', 'Are you sure you want to delete this item?'),
                'method' => 'post',
            ],
        ]) ?>
    </p>

    <?= DetailView::widget([
        'model' => $model,
        'attributes' => [
            'id',
            'user_id',
            'mail_template_id',
            'status',
            'placeholders:ntext',
            'created_at',
            'date_send',
        ],
    ]) ?>

</div>